export const DepartmentInit = '/department/init';            // 数据初始     --参数：无
export const DepartmentTotalCount = '/department/totalCount';// 数据总数     --参数：无
export const DepartmentQueryCount = '/department/queryCount';// 查询数据总数 --参数：queryName
export const DepartmentQuery = '/department/query';          // 数据查询     --参数：queryName
export const DepartmentPaginate = '/department/paginate';    // 数据分页     --参数：queryName,pageNumber
export const DepartmentLook = '/department/look';            // 查看部门     --参数：id
export const DepartmentAdd = '/department/add';              // 添加部门     --参数：name,address,phone,other,active
export const DepartmentEdit = '/department/edit';            // 修改部门     --参数：id,name,address,phone,other,active
export const DepartmentDelete = '/department/delete';        // 删除部门     --参数：id
export const DepartmentExist = '/department/exist';          // 部门是否存在 --参数：id
export const DepartmentActive = '/department/active';        // 激活部门     --参数：id
export const DepartmentAbandon = '/department/abandon';      // 注销部门     --参数：id
export const DepartmentState = '/department/state';          // 部门状态     --参数：id
export const DepartmentName = '/department/name';            // 检测名称     --参数：name
export const DepartmentAddress = '/department/address';      // 检测地址     --参数：address
export const DepartmentPhone = '/department/phone';          // 检测电话     --参数：phone
